ci:
    skip: [python-safety-dependencies-check]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: requirements-txt-fixer

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake

  - repo: https://github.com/miki725/importanize/
    rev: 'master'
    hooks:
      - id: importanize
        language_version: python3
        language: python
        args: [ --verbose ]

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        exclude: ^.*__init__.py$
        stages: [commit, push, manual]

  - repo: https://github.com/hhatto/autopep8
    rev:  v2.0.4
    hooks:
      - id: autopep8
        args: [--in-place, --aggressive, --aggressive, --max-line-length=79]

  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter

  - repo: https://github.com/thibaudcolas/curlylint
    rev: v0.13.1
    hooks:
      - id: curlylint

#  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
#    rev: v1.3.1
#    hooks:
#      - id: python-safety-dependencies-check
#        files: requirements

  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.8'
    hooks:
      - id: bandit

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        args:
          - --fix
          - --line-length=120

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=120]

  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.2'
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["-C", "./app", "--without-hashes", "--without=dev", "-f", "requirements.txt", "-o", "./app/requirements.txt"]
