[theme]
#primaryColor="#f21111"
#backgroundColor="#0e1117"
#secondaryBackgroundColor="#31333F"
#textColor="#fafafa"
# -- dark chocolate --
#primaryColor="#2c3e50"
#backgroundColor="#1a1a1a"
#secondaryBackgroundColor="#333333"
#textColor="#dcdcdc"
# -- midnight feast --
#primaryColor="#2c3e50"
#backgroundColor="#1a1a1a"
#secondaryBackgroundColor="#333333"
#textColor="#dcdcdc"
# -- umami delight --
#primaryColor="#556b2f"
#backgroundColor="#1a1a1a"
#secondaryBackgroundColor="#4c721d"
#textColor="#f0e68c"
# -- spicy wasabi --
#primaryColor="#33CC99"
#backgroundColor="#222222"
#secondaryBackgroundColor="#333333"
#textColor="#f0f0f0"
# -- night sky --
#primaryColor="#a62c81"
#backgroundColor="#191919"
#secondaryBackgroundColor="#222222"
#textColor="#dddddd"
# -- modern minimalist --
#primaryColor="#00bcd4"
#backgroundColor="#212121"
#secondaryBackgroundColor="#303030"
#textColor="#e0e0e0"
# -- cocoa indulgence --
#primaryColor="#8b4513"
#backgroundColor="#1c1c1c"
#secondaryBackgroundColor="#3d2c1f"
#textColor="#ffe4b5"
# -- spicy heat --
primaryColor="#d9534f"
 backgroundColor="#000000"
 secondaryBackgroundColor="#8b0000"
 textColor="#b0c4de"
font="monospace"
