[connections.supabase]
SUPABASE_URL = "https://rwiascqxcbessckesahh.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ3aWFzY3F4Y2Jlc3Nja2VzYWhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTE1NjQxODgsImV4cCI6MjAyNzE0MDE4OH0.j9sGKfCxN1JhxfFUElCR68zK_EWIMhStWrZjA6ZFUEw"
